### ISSUE TITLE
Deploy contracts by hardhat

### ISSUE THREAD

**Issue by Skyge** [wighawag/buidler-deploy-ts-test#3]
Hey, how should I deploy the contracts in this repo? Cause I find there are two folders: `scripts` and `deploy`, according to the hardhat doc, I should run ` hardhat run scripts/greet.ts --network kovan` to deploy, so when should I use `deploy`?

**Comment by wighawag** [comment]
Hi @Skyge 
if you look at the scripts in the `scripts` folder they are just scripts, they do not do any deployments

With `hardhat-deploy` plugin, deployments are done in the special `deploy` folder where they are executed in order

You can still use `scripts` for deployment if you wish but the `deploy` folder offers more possibilities. It for exampel support declaring dependencies between various deploy script, plus the deployemnt performed there can be easily performed when testing, see : https://github.com/wighawag/hardhat-deploy#testing-deployed-contracts
